### PR TITLE
Added Coding Tutorial

### PR DESCRIPTION
**Pull request by fgiuliani**
Added "Public bookmark list and URL shortener with Fauna, Next.js and Auth0"

### CODE REVIEW

**Comment by fgiuliani** [comment]
@n400 does this work for the repo?

**Review by n400 — APPROVED** [review]

**Comment by n400** [comment]
yes, thank you!

**Comment by fgiuliani** [comment]
@n400 how should I do to merge it?

**Comment by n400** [comment]
Sorry, I merged it. Thank you!

**Pull request merged**
